/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type {
  AccountAddFavorite200,
  AccountAddFavoriteBody,
  AccountAddFavoriteParams,
  AccountAddToWatchlist200,
  AccountAddToWatchlistBody,
  AccountAddToWatchlistParams,
  AccountDetails200,
  AccountDetailsParams,
  AccountFavoriteTv200,
  AccountFavoriteTvParams,
  AccountGetFavorites200,
  AccountGetFavoritesParams,
  AccountLists200,
  AccountListsParams,
  AccountRatedMovies200,
  AccountRatedMoviesParams,
  AccountRatedTv200,
  AccountRatedTvEpisodes200,
  AccountRatedTvEpisodesParams,
  AccountRatedTvParams,
  AccountWatchlistMovies200,
  AccountWatchlistMoviesParams,
  AccountWatchlistTv200,
  AccountWatchlistTvParams,
  AlternativeNamesCopy200,
  AuthenticationCreateGuestSession200,
  AuthenticationCreateRequestToken200,
  AuthenticationCreateSession200,
  AuthenticationCreateSessionBody,
  AuthenticationCreateSessionFromLogin200,
  AuthenticationCreateSessionFromLoginBody,
  AuthenticationCreateSessionFromV4Token200,
  AuthenticationCreateSessionFromV4TokenBody,
  AuthenticationDeleteSession200,
  AuthenticationDeleteSessionBody,
  AuthenticationValidateKey200,
  CertificationMovieList200,
  CertificationsTvList200,
  ChangesMovieList200,
  ChangesMovieListParams,
  ChangesPeopleList200,
  ChangesPeopleListParams,
  ChangesTvList200,
  ChangesTvListParams,
  CollectionDetails200,
  CollectionDetailsParams,
  CollectionImages200,
  CollectionImagesParams,
  CollectionTranslations200,
  CompanyAlternativeNames200,
  CompanyDetails200,
  CompanyImages200,
  ConfigurationCountries200Item,
  ConfigurationCountriesParams,
  ConfigurationDetails200,
  ConfigurationJobs200Item,
  ConfigurationLanguages200Item,
  ConfigurationTimezones200Item,
  CreditDetails200,
  CreditDetailsParams,
  DetailsCopy200,
  DiscoverMovie200,
  DiscoverMovieParams,
  DiscoverTv200,
  DiscoverTvParams,
  FindById200,
  FindByIdParams,
  GenreMovieList200,
  GenreMovieListParams,
  GenreTvList200,
  GenreTvListParams,
  GuestSessionRatedMovies200,
  GuestSessionRatedMoviesParams,
  GuestSessionRatedTv200,
  GuestSessionRatedTvEpisodes200,
  GuestSessionRatedTvEpisodesParams,
  GuestSessionRatedTvParams,
  KeywordDetails200,
  KeywordMovies200,
  KeywordMoviesParams,
  ListAddMovie200,
  ListAddMovieBody,
  ListAddMovieParams,
  ListCheckItemStatus200,
  ListCheckItemStatusParams,
  ListClear200,
  ListClearParams,
  ListCreate200,
  ListCreateBody,
  ListCreateParams,
  ListDelete200,
  ListDeleteParams,
  ListDetails200,
  ListDetailsParams,
  ListRemoveMovie200,
  ListRemoveMovieBody,
  ListRemoveMovieParams,
  ListsCopy200,
  ListsCopyParams,
  MovieAccountStates200,
  MovieAccountStatesParams,
  MovieAddRating200,
  MovieAddRatingBody,
  MovieAddRatingParams,
  MovieAlternativeTitles200,
  MovieAlternativeTitlesParams,
  MovieChanges200,
  MovieChangesParams,
  MovieCredits200,
  MovieCreditsParams,
  MovieDeleteRating200,
  MovieDeleteRatingParams,
  MovieDetails200,
  MovieDetailsParams,
  MovieExternalIds200,
  MovieImages200,
  MovieImagesParams,
  MovieKeywords200,
  MovieLatestId200,
  MovieLists200,
  MovieListsParams,
  MovieNowPlayingList200,
  MovieNowPlayingListParams,
  MoviePopularList200,
  MoviePopularListParams,
  MovieRecommendations200,
  MovieRecommendationsParams,
  MovieReleaseDates200,
  MovieReviews200,
  MovieReviewsParams,
  MovieSimilar200,
  MovieSimilarParams,
  MovieTopRatedList200,
  MovieTopRatedListParams,
  MovieTranslations200,
  MovieUpcomingList200,
  MovieUpcomingListParams,
  MovieVideos200,
  MovieVideosParams,
  MovieWatchProviders200,
  NetworkDetails200,
  PersonChanges200,
  PersonChangesParams,
  PersonCombinedCredits200,
  PersonCombinedCreditsParams,
  PersonDetails200,
  PersonDetailsParams,
  PersonExternalIds200,
  PersonImages200,
  PersonLatestId200,
  PersonMovieCredits200,
  PersonMovieCreditsParams,
  PersonPopularList200,
  PersonPopularListParams,
  PersonTaggedImages200,
  PersonTaggedImagesParams,
  PersonTvCredits200,
  PersonTvCreditsParams,
  ReviewDetails200,
  SearchCollection200,
  SearchCollectionParams,
  SearchCompany200,
  SearchCompanyParams,
  SearchKeyword200,
  SearchKeywordParams,
  SearchMovie200,
  SearchMovieParams,
  SearchMulti200,
  SearchMultiParams,
  SearchPerson200,
  SearchPersonParams,
  SearchTv200,
  SearchTvParams,
  Translations200,
  TrendingAll200,
  TrendingAllParams,
  TrendingMovies200,
  TrendingMoviesParams,
  TrendingPeople200,
  TrendingPeopleParams,
  TrendingTv200,
  TrendingTvParams,
  TvEpisodeAccountStates200,
  TvEpisodeAccountStatesParams,
  TvEpisodeAddRating200,
  TvEpisodeAddRatingBody,
  TvEpisodeAddRatingParams,
  TvEpisodeChangesById200,
  TvEpisodeCredits200,
  TvEpisodeCreditsParams,
  TvEpisodeDeleteRating200,
  TvEpisodeDeleteRatingParams,
  TvEpisodeDetails200,
  TvEpisodeDetailsParams,
  TvEpisodeExternalIds200,
  TvEpisodeGroupDetails200,
  TvEpisodeImages200,
  TvEpisodeImagesParams,
  TvEpisodeTranslations200,
  TvEpisodeVideos200,
  TvEpisodeVideosParams,
  TvSeasonAccountStates200,
  TvSeasonAccountStatesParams,
  TvSeasonAggregateCredits200,
  TvSeasonAggregateCreditsParams,
  TvSeasonChangesById200,
  TvSeasonChangesByIdParams,
  TvSeasonCredits200,
  TvSeasonCreditsParams,
  TvSeasonDetails200,
  TvSeasonDetailsParams,
  TvSeasonExternalIds200,
  TvSeasonImages200,
  TvSeasonImagesParams,
  TvSeasonTranslations200,
  TvSeasonVideos200,
  TvSeasonVideosParams,
  TvSeasonWatchProviders200,
  TvSeasonWatchProvidersParams,
  TvSeriesAccountStates200,
  TvSeriesAccountStatesParams,
  TvSeriesAddRating200,
  TvSeriesAddRatingBody,
  TvSeriesAddRatingParams,
  TvSeriesAggregateCredits200,
  TvSeriesAggregateCreditsParams,
  TvSeriesAiringTodayList200,
  TvSeriesAiringTodayListParams,
  TvSeriesAlternativeTitles200,
  TvSeriesChanges200,
  TvSeriesChangesParams,
  TvSeriesContentRatings200,
  TvSeriesCredits200,
  TvSeriesCreditsParams,
  TvSeriesDeleteRating200,
  TvSeriesDeleteRatingParams,
  TvSeriesDetails200,
  TvSeriesDetailsParams,
  TvSeriesEpisodeGroups200,
  TvSeriesExternalIds200,
  TvSeriesImages200,
  TvSeriesImagesParams,
  TvSeriesKeywords200,
  TvSeriesLatestId200,
  TvSeriesOnTheAirList200,
  TvSeriesOnTheAirListParams,
  TvSeriesPopularList200,
  TvSeriesPopularListParams,
  TvSeriesRecommendations200,
  TvSeriesRecommendationsParams,
  TvSeriesReviews200,
  TvSeriesReviewsParams,
  TvSeriesScreenedTheatrically200,
  TvSeriesSimilar200,
  TvSeriesSimilarParams,
  TvSeriesTopRatedList200,
  TvSeriesTopRatedListParams,
  TvSeriesTranslations200,
  TvSeriesVideos200,
  TvSeriesVideosParams,
  TvSeriesWatchProviders200,
  WatchProviderTvList200,
  WatchProviderTvListParams,
  WatchProvidersAvailableRegions200,
  WatchProvidersAvailableRegionsParams,
  WatchProvidersMovieList200,
  WatchProvidersMovieListParams
} from '../model/types';

import { tmdbClient } from './tmdbClient';
import type { BodyType } from './tmdbClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Test your API Key to see if it's valid.
 * @summary Validate Key
 */
export const authenticationValidateKey = (

 options?: SecondParameter<typeof tmdbClient<AuthenticationValidateKey200>>,) => {
      return tmdbClient<AuthenticationValidateKey200>(
      {url: `https://api.themoviedb.org/3/authentication`, method: 'GET'
    },
      options);
    }

/**
 * Get the public details of an account on TMDB.
 * @summary Details
 */
export const accountDetails = (
    accountId: number,
    params?: AccountDetailsParams,
 options?: SecondParameter<typeof tmdbClient<AccountDetails200>>,) => {
      return tmdbClient<AccountDetails200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Mark a movie or TV show as a favourite.
 * @summary Add Favorite
 */
export const accountAddFavorite = (
    accountId: number,
    accountAddFavoriteBody?: BodyType<AccountAddFavoriteBody>,
    params?: AccountAddFavoriteParams,
 options?: SecondParameter<typeof tmdbClient<AccountAddFavorite200>>,) => {
      return tmdbClient<AccountAddFavorite200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/favorite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountAddFavoriteBody,
        params
    },
      options);
    }

/**
 * Add a movie or TV show to your watchlist.
 * @summary Add To Watchlist
 */
export const accountAddToWatchlist = (
    accountId: number,
    accountAddToWatchlistBody?: BodyType<AccountAddToWatchlistBody>,
    params?: AccountAddToWatchlistParams,
 options?: SecondParameter<typeof tmdbClient<AccountAddToWatchlist200>>,) => {
      return tmdbClient<AccountAddToWatchlist200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/watchlist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountAddToWatchlistBody,
        params
    },
      options);
    }

/**
 * Get a users list of favourite movies.
 * @summary Favorite Movies
 */
export const accountGetFavorites = (
    accountId: number,
    params?: AccountGetFavoritesParams,
 options?: SecondParameter<typeof tmdbClient<AccountGetFavorites200>>,) => {
      return tmdbClient<AccountGetFavorites200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/favorite/movies`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a users list of favourite TV shows.
 * @summary Favorite TV
 */
export const accountFavoriteTv = (
    accountId: number,
    params?: AccountFavoriteTvParams,
 options?: SecondParameter<typeof tmdbClient<AccountFavoriteTv200>>,) => {
      return tmdbClient<AccountFavoriteTv200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/favorite/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a users list of custom lists.
 * @summary Lists
 */
export const accountLists = (
    accountId: number,
    params?: AccountListsParams,
 options?: SecondParameter<typeof tmdbClient<AccountLists200>>,) => {
      return tmdbClient<AccountLists200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/lists`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a users list of rated movies.
 * @summary Rated Movies
 */
export const accountRatedMovies = (
    accountId: number,
    params?: AccountRatedMoviesParams,
 options?: SecondParameter<typeof tmdbClient<AccountRatedMovies200>>,) => {
      return tmdbClient<AccountRatedMovies200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/rated/movies`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a users list of rated TV shows.
 * @summary Rated TV
 */
export const accountRatedTv = (
    accountId: number,
    params?: AccountRatedTvParams,
 options?: SecondParameter<typeof tmdbClient<AccountRatedTv200>>,) => {
      return tmdbClient<AccountRatedTv200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/rated/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a users list of rated TV episodes.
 * @summary Rated TV Episodes
 */
export const accountRatedTvEpisodes = (
    accountId: number,
    params?: AccountRatedTvEpisodesParams,
 options?: SecondParameter<typeof tmdbClient<AccountRatedTvEpisodes200>>,) => {
      return tmdbClient<AccountRatedTvEpisodes200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/rated/tv/episodes`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of movies added to a users watchlist.
 * @summary Watchlist Movies
 */
export const accountWatchlistMovies = (
    accountId: number,
    params?: AccountWatchlistMoviesParams,
 options?: SecondParameter<typeof tmdbClient<AccountWatchlistMovies200>>,) => {
      return tmdbClient<AccountWatchlistMovies200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/watchlist/movies`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of TV shows added to a users watchlist.
 * @summary Watchlist TV
 */
export const accountWatchlistTv = (
    accountId: number,
    params?: AccountWatchlistTvParams,
 options?: SecondParameter<typeof tmdbClient<AccountWatchlistTv200>>,) => {
      return tmdbClient<AccountWatchlistTv200>(
      {url: `https://api.themoviedb.org/3/account/${accountId}/watchlist/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Create Guest Session
 */
export const authenticationCreateGuestSession = (

 options?: SecondParameter<typeof tmdbClient<AuthenticationCreateGuestSession200>>,) => {
      return tmdbClient<AuthenticationCreateGuestSession200>(
      {url: `https://api.themoviedb.org/3/authentication/guest_session/new`, method: 'GET'
    },
      options);
    }

/**
 * @summary Create Request Token
 */
export const authenticationCreateRequestToken = (

 options?: SecondParameter<typeof tmdbClient<AuthenticationCreateRequestToken200>>,) => {
      return tmdbClient<AuthenticationCreateRequestToken200>(
      {url: `https://api.themoviedb.org/3/authentication/token/new`, method: 'GET'
    },
      options);
    }

/**
 * @summary Create Session
 */
export const authenticationCreateSession = (
    authenticationCreateSessionBody?: BodyType<AuthenticationCreateSessionBody>,
 options?: SecondParameter<typeof tmdbClient<AuthenticationCreateSession200>>,) => {
      return tmdbClient<AuthenticationCreateSession200>(
      {url: `https://api.themoviedb.org/3/authentication/session/new`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationCreateSessionBody
    },
      options);
    }

/**
 * @summary Create Session (from v4 token)
 */
export const authenticationCreateSessionFromV4Token = (
    authenticationCreateSessionFromV4TokenBody?: BodyType<AuthenticationCreateSessionFromV4TokenBody>,
 options?: SecondParameter<typeof tmdbClient<AuthenticationCreateSessionFromV4Token200>>,) => {
      return tmdbClient<AuthenticationCreateSessionFromV4Token200>(
      {url: `https://api.themoviedb.org/3/authentication/session/convert/4`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationCreateSessionFromV4TokenBody
    },
      options);
    }

/**
 * This method allows an application to validate a request token by entering a username and password.
 * @summary Create Session (with login)
 */
export const authenticationCreateSessionFromLogin = (
    authenticationCreateSessionFromLoginBody?: BodyType<AuthenticationCreateSessionFromLoginBody>,
 options?: SecondParameter<typeof tmdbClient<AuthenticationCreateSessionFromLogin200>>,) => {
      return tmdbClient<AuthenticationCreateSessionFromLogin200>(
      {url: `https://api.themoviedb.org/3/authentication/token/validate_with_login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationCreateSessionFromLoginBody
    },
      options);
    }

/**
 * @summary Delete Session
 */
export const authenticationDeleteSession = (
    authenticationDeleteSessionBody?: BodyType<AuthenticationDeleteSessionBody>,
 options?: SecondParameter<typeof tmdbClient<AuthenticationDeleteSession200>>,) => {
      return tmdbClient<AuthenticationDeleteSession200>(
      {url: `https://api.themoviedb.org/3/authentication/session`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: authenticationDeleteSessionBody
    },
      options);
    }

/**
 * Get an up to date list of the officially supported movie certifications on TMDB.
 * @summary Movie Certifications
 */
export const certificationMovieList = (

 options?: SecondParameter<typeof tmdbClient<CertificationMovieList200>>,) => {
      return tmdbClient<CertificationMovieList200>(
      {url: `https://api.themoviedb.org/3/certification/movie/list`, method: 'GET'
    },
      options);
    }

/**
 * @summary TV Certifications
 */
export const certificationsTvList = (

 options?: SecondParameter<typeof tmdbClient<CertificationsTvList200>>,) => {
      return tmdbClient<CertificationsTvList200>(
      {url: `https://api.themoviedb.org/3/certification/tv/list`, method: 'GET'
    },
      options);
    }

/**
 * Get a list of all of the movie ids that have been changed in the past 24 hours.
 * @summary Movie List
 */
export const changesMovieList = (
    params?: ChangesMovieListParams,
 options?: SecondParameter<typeof tmdbClient<ChangesMovieList200>>,) => {
      return tmdbClient<ChangesMovieList200>(
      {url: `https://api.themoviedb.org/3/movie/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary People List
 */
export const changesPeopleList = (
    params?: ChangesPeopleListParams,
 options?: SecondParameter<typeof tmdbClient<ChangesPeopleList200>>,) => {
      return tmdbClient<ChangesPeopleList200>(
      {url: `https://api.themoviedb.org/3/person/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary TV List
 */
export const changesTvList = (
    params?: ChangesTvListParams,
 options?: SecondParameter<typeof tmdbClient<ChangesTvList200>>,) => {
      return tmdbClient<ChangesTvList200>(
      {url: `https://api.themoviedb.org/3/tv/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get collection details by ID.
 * @summary Details
 */
export const collectionDetails = (
    collectionId: number,
    params?: CollectionDetailsParams,
 options?: SecondParameter<typeof tmdbClient<CollectionDetails200>>,) => {
      return tmdbClient<CollectionDetails200>(
      {url: `https://api.themoviedb.org/3/collection/${collectionId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the images that belong to a collection.
 * @summary Images
 */
export const collectionImages = (
    collectionId: number,
    params?: CollectionImagesParams,
 options?: SecondParameter<typeof tmdbClient<CollectionImages200>>,) => {
      return tmdbClient<CollectionImages200>(
      {url: `https://api.themoviedb.org/3/collection/${collectionId}/images`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Translations
 */
export const collectionTranslations = (
    collectionId: number,
 options?: SecondParameter<typeof tmdbClient<CollectionTranslations200>>,) => {
      return tmdbClient<CollectionTranslations200>(
      {url: `https://api.themoviedb.org/3/collection/${collectionId}/translations`, method: 'GET'
    },
      options);
    }

/**
 * Get the company details by ID.
 * @summary Details
 */
export const companyDetails = (
    companyId: number,
 options?: SecondParameter<typeof tmdbClient<CompanyDetails200>>,) => {
      return tmdbClient<CompanyDetails200>(
      {url: `https://api.themoviedb.org/3/company/${companyId}`, method: 'GET'
    },
      options);
    }

/**
 * Get the company details by ID.
 * @summary Alternative Names
 */
export const companyAlternativeNames = (
    companyId: number,
 options?: SecondParameter<typeof tmdbClient<CompanyAlternativeNames200>>,) => {
      return tmdbClient<CompanyAlternativeNames200>(
      {url: `https://api.themoviedb.org/3/company/${companyId}/alternative_names`, method: 'GET'
    },
      options);
    }

/**
 * Get the company logos by id.
 * @summary Images
 */
export const companyImages = (
    companyId: number,
 options?: SecondParameter<typeof tmdbClient<CompanyImages200>>,) => {
      return tmdbClient<CompanyImages200>(
      {url: `https://api.themoviedb.org/3/company/${companyId}/images`, method: 'GET'
    },
      options);
    }

/**
 * Query the API configuration details.
 * @summary Details
 */
export const configurationDetails = (

 options?: SecondParameter<typeof tmdbClient<ConfigurationDetails200>>,) => {
      return tmdbClient<ConfigurationDetails200>(
      {url: `https://api.themoviedb.org/3/configuration`, method: 'GET'
    },
      options);
    }

/**
 * Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
 * @summary Countries
 */
export const configurationCountries = (
    params?: ConfigurationCountriesParams,
 options?: SecondParameter<typeof tmdbClient<ConfigurationCountries200Item[]>>,) => {
      return tmdbClient<ConfigurationCountries200Item[]>(
      {url: `https://api.themoviedb.org/3/configuration/countries`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of the jobs and departments we use on TMDB.
 * @summary Jobs
 */
export const configurationJobs = (

 options?: SecondParameter<typeof tmdbClient<ConfigurationJobs200Item[]>>,) => {
      return tmdbClient<ConfigurationJobs200Item[]>(
      {url: `https://api.themoviedb.org/3/configuration/jobs`, method: 'GET'
    },
      options);
    }

/**
 * Get the list of languages (ISO 639-1 tags) used throughout TMDB.
 * @summary Languages
 */
export const configurationLanguages = (

 options?: SecondParameter<typeof tmdbClient<ConfigurationLanguages200Item[]>>,) => {
      return tmdbClient<ConfigurationLanguages200Item[]>(
      {url: `https://api.themoviedb.org/3/configuration/languages`, method: 'GET'
    },
      options);
    }

/**
 * Get a list of the officially supported translations on TMDB.
 * @summary Primary Translations
 */
export const configurationPrimaryTranslations = (

 options?: SecondParameter<typeof tmdbClient<string[]>>,) => {
      return tmdbClient<string[]>(
      {url: `https://api.themoviedb.org/3/configuration/primary_translations`, method: 'GET'
    },
      options);
    }

/**
 * Get the list of timezones used throughout TMDB.
 * @summary Timezones
 */
export const configurationTimezones = (

 options?: SecondParameter<typeof tmdbClient<ConfigurationTimezones200Item[]>>,) => {
      return tmdbClient<ConfigurationTimezones200Item[]>(
      {url: `https://api.themoviedb.org/3/configuration/timezones`, method: 'GET'
    },
      options);
    }

/**
 * Get a movie or TV credit details by ID.
 * @summary Details
 */
export const creditDetails = (
    creditId: string,
    params?: CreditDetailsParams,
 options?: SecondParameter<typeof tmdbClient<CreditDetails200>>,) => {
      return tmdbClient<CreditDetails200>(
      {url: `https://api.themoviedb.org/3/credit/${creditId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Find movies using over 30 filters and sort options.
 * @summary Movie
 */
export const discoverMovie = (
    params?: DiscoverMovieParams,
 options?: SecondParameter<typeof tmdbClient<DiscoverMovie200>>,) => {
      return tmdbClient<DiscoverMovie200>(
      {url: `https://api.themoviedb.org/3/discover/movie`, method: 'GET',
        params
    },
      options);
    }

/**
 * Find TV shows using over 30 filters and sort options.
 * @summary TV
 */
export const discoverTv = (
    params?: DiscoverTvParams,
 options?: SecondParameter<typeof tmdbClient<DiscoverTv200>>,) => {
      return tmdbClient<DiscoverTv200>(
      {url: `https://api.themoviedb.org/3/discover/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * Find data by external ID's.
 * @summary Find By ID
 */
export const findById = (
    externalId: string,
    params: FindByIdParams,
 options?: SecondParameter<typeof tmdbClient<FindById200>>,) => {
      return tmdbClient<FindById200>(
      {url: `https://api.themoviedb.org/3/find/${externalId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of official genres for movies.
 * @summary Movie List
 */
export const genreMovieList = (
    params?: GenreMovieListParams,
 options?: SecondParameter<typeof tmdbClient<GenreMovieList200>>,) => {
      return tmdbClient<GenreMovieList200>(
      {url: `https://api.themoviedb.org/3/genre/movie/list`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of official genres for TV shows.
 * @summary TV List
 */
export const genreTvList = (
    params?: GenreTvListParams,
 options?: SecondParameter<typeof tmdbClient<GenreTvList200>>,) => {
      return tmdbClient<GenreTvList200>(
      {url: `https://api.themoviedb.org/3/genre/tv/list`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rated movies for a guest session.
 * @summary Rated Movies
 */
export const guestSessionRatedMovies = (
    guestSessionId: string,
    params?: GuestSessionRatedMoviesParams,
 options?: SecondParameter<typeof tmdbClient<GuestSessionRatedMovies200>>,) => {
      return tmdbClient<GuestSessionRatedMovies200>(
      {url: `https://api.themoviedb.org/3/guest_session/${guestSessionId}/rated/movies`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rated TV shows for a guest session.
 * @summary Rated TV
 */
export const guestSessionRatedTv = (
    guestSessionId: string,
    params?: GuestSessionRatedTvParams,
 options?: SecondParameter<typeof tmdbClient<GuestSessionRatedTv200>>,) => {
      return tmdbClient<GuestSessionRatedTv200>(
      {url: `https://api.themoviedb.org/3/guest_session/${guestSessionId}/rated/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rated TV episodes for a guest session.
 * @summary Rated TV Episodes
 */
export const guestSessionRatedTvEpisodes = (
    guestSessionId: string,
    params?: GuestSessionRatedTvEpisodesParams,
 options?: SecondParameter<typeof tmdbClient<GuestSessionRatedTvEpisodes200>>,) => {
      return tmdbClient<GuestSessionRatedTvEpisodes200>(
      {url: `https://api.themoviedb.org/3/guest_session/${guestSessionId}/rated/tv/episodes`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Details
 */
export const keywordDetails = (
    keywordId: number,
 options?: SecondParameter<typeof tmdbClient<KeywordDetails200>>,) => {
      return tmdbClient<KeywordDetails200>(
      {url: `https://api.themoviedb.org/3/keyword/${keywordId}`, method: 'GET'
    },
      options);
    }

/**
 * @summary Movies
 */
export const keywordMovies = (
    keywordId: string,
    params?: KeywordMoviesParams,
 options?: SecondParameter<typeof tmdbClient<KeywordMovies200>>,) => {
      return tmdbClient<KeywordMovies200>(
      {url: `https://api.themoviedb.org/3/keyword/${keywordId}/movies`, method: 'GET',
        params
    },
      options);
    }

/**
 * Add a movie to a list.
 * @summary Add Movie
 */
export const listAddMovie = (
    listId: number,
    params: ListAddMovieParams,
    listAddMovieBody?: BodyType<ListAddMovieBody>,
 options?: SecondParameter<typeof tmdbClient<ListAddMovie200>>,) => {
      return tmdbClient<ListAddMovie200>(
      {url: `https://api.themoviedb.org/3/list/${listId}/add_item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listAddMovieBody,
        params
    },
      options);
    }

/**
 * Use this method to check if an item has already been added to the list.
 * @summary Check Item Status
 */
export const listCheckItemStatus = (
    listId: number,
    params?: ListCheckItemStatusParams,
 options?: SecondParameter<typeof tmdbClient<ListCheckItemStatus200>>,) => {
      return tmdbClient<ListCheckItemStatus200>(
      {url: `https://api.themoviedb.org/3/list/${listId}/item_status`, method: 'GET',
        params
    },
      options);
    }

/**
 * Clear all items from a list.
 * @summary Clear
 */
export const listClear = (
    listId: number,
    params: ListClearParams,
 options?: SecondParameter<typeof tmdbClient<ListClear200>>,) => {
      return tmdbClient<ListClear200>(
      {url: `https://api.themoviedb.org/3/list/${listId}/clear`, method: 'POST',
        params
    },
      options);
    }

/**
 * @summary Create
 */
export const listCreate = (
    params: ListCreateParams,
    listCreateBody?: BodyType<ListCreateBody>,
 options?: SecondParameter<typeof tmdbClient<ListCreate200>>,) => {
      return tmdbClient<ListCreate200>(
      {url: `https://api.themoviedb.org/3/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listCreateBody,
        params
    },
      options);
    }

/**
 * Delete a list.
 * @summary Delete
 */
export const listDelete = (
    listId: number,
    params: ListDeleteParams,
 options?: SecondParameter<typeof tmdbClient<ListDelete200>>,) => {
      return tmdbClient<ListDelete200>(
      {url: `https://api.themoviedb.org/3/list/${listId}`, method: 'DELETE',
        params
    },
      options);
    }

/**
 * @summary Details
 */
export const listDetails = (
    listId: number,
    params?: ListDetailsParams,
 options?: SecondParameter<typeof tmdbClient<ListDetails200>>,) => {
      return tmdbClient<ListDetails200>(
      {url: `https://api.themoviedb.org/3/list/${listId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Remove a movie from a list.
 * @summary Remove Movie
 */
export const listRemoveMovie = (
    listId: number,
    params: ListRemoveMovieParams,
    listRemoveMovieBody?: BodyType<ListRemoveMovieBody>,
 options?: SecondParameter<typeof tmdbClient<ListRemoveMovie200>>,) => {
      return tmdbClient<ListRemoveMovie200>(
      {url: `https://api.themoviedb.org/3/list/${listId}/remove_item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listRemoveMovieBody,
        params
    },
      options);
    }

/**
 * Get a list of movies that are currently in theatres.
 * @summary Now Playing
 */
export const movieNowPlayingList = (
    params?: MovieNowPlayingListParams,
 options?: SecondParameter<typeof tmdbClient<MovieNowPlayingList200>>,) => {
      return tmdbClient<MovieNowPlayingList200>(
      {url: `https://api.themoviedb.org/3/movie/now_playing`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of movies ordered by popularity.
 * @summary Popular
 */
export const moviePopularList = (
    params?: MoviePopularListParams,
 options?: SecondParameter<typeof tmdbClient<MoviePopularList200>>,) => {
      return tmdbClient<MoviePopularList200>(
      {url: `https://api.themoviedb.org/3/movie/popular`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of movies ordered by rating.
 * @summary Top Rated
 */
export const movieTopRatedList = (
    params?: MovieTopRatedListParams,
 options?: SecondParameter<typeof tmdbClient<MovieTopRatedList200>>,) => {
      return tmdbClient<MovieTopRatedList200>(
      {url: `https://api.themoviedb.org/3/movie/top_rated`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of movies that are being released soon.
 * @summary Upcoming
 */
export const movieUpcomingList = (
    params?: MovieUpcomingListParams,
 options?: SecondParameter<typeof tmdbClient<MovieUpcomingList200>>,) => {
      return tmdbClient<MovieUpcomingList200>(
      {url: `https://api.themoviedb.org/3/movie/upcoming`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the top level details of a movie by ID.
 * @summary Details
 */
export const movieDetails = (
    movieId: number,
    params?: MovieDetailsParams,
 options?: SecondParameter<typeof tmdbClient<MovieDetails200>>,) => {
      return tmdbClient<MovieDetails200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rating, watchlist and favourite status of an account.
 * @summary Account States
 */
export const movieAccountStates = (
    movieId: number,
    params?: MovieAccountStatesParams,
 options?: SecondParameter<typeof tmdbClient<MovieAccountStates200>>,) => {
      return tmdbClient<MovieAccountStates200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/account_states`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the alternative titles for a movie.
 * @summary Alternative Titles
 */
export const movieAlternativeTitles = (
    movieId: number,
    params?: MovieAlternativeTitlesParams,
 options?: SecondParameter<typeof tmdbClient<MovieAlternativeTitles200>>,) => {
      return tmdbClient<MovieAlternativeTitles200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/alternative_titles`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the recent changes for a movie.
 * @summary Changes
 */
export const movieChanges = (
    movieId: number,
    params?: MovieChangesParams,
 options?: SecondParameter<typeof tmdbClient<MovieChanges200>>,) => {
      return tmdbClient<MovieChanges200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Credits
 */
export const movieCredits = (
    movieId: number,
    params?: MovieCreditsParams,
 options?: SecondParameter<typeof tmdbClient<MovieCredits200>>,) => {
      return tmdbClient<MovieCredits200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary External IDs
 */
export const movieExternalIds = (
    movieId: number,
 options?: SecondParameter<typeof tmdbClient<MovieExternalIds200>>,) => {
      return tmdbClient<MovieExternalIds200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/external_ids`, method: 'GET'
    },
      options);
    }

/**
 * Get the images that belong to a movie.
 * @summary Images
 */
export const movieImages = (
    movieId: number,
    params?: MovieImagesParams,
 options?: SecondParameter<typeof tmdbClient<MovieImages200>>,) => {
      return tmdbClient<MovieImages200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/images`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Keywords
 */
export const movieKeywords = (
    movieId: string,
 options?: SecondParameter<typeof tmdbClient<MovieKeywords200>>,) => {
      return tmdbClient<MovieKeywords200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/keywords`, method: 'GET'
    },
      options);
    }

/**
 * Get the newest movie ID.
 * @summary Latest
 */
export const movieLatestId = (

 options?: SecondParameter<typeof tmdbClient<MovieLatestId200>>,) => {
      return tmdbClient<MovieLatestId200>(
      {url: `https://api.themoviedb.org/3/movie/latest`, method: 'GET'
    },
      options);
    }

/**
 * Get the lists that a movie has been added to.
 * @summary Lists
 */
export const movieLists = (
    movieId: number,
    params?: MovieListsParams,
 options?: SecondParameter<typeof tmdbClient<MovieLists200>>,) => {
      return tmdbClient<MovieLists200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/lists`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Recommendations
 */
export const movieRecommendations = (
    movieId: number,
    params?: MovieRecommendationsParams,
 options?: SecondParameter<typeof tmdbClient<MovieRecommendations200>>,) => {
      return tmdbClient<MovieRecommendations200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/recommendations`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the release dates and certifications for a movie.
 * @summary Release Dates
 */
export const movieReleaseDates = (
    movieId: number,
 options?: SecondParameter<typeof tmdbClient<MovieReleaseDates200>>,) => {
      return tmdbClient<MovieReleaseDates200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/release_dates`, method: 'GET'
    },
      options);
    }

/**
 * Get the user reviews for a movie.
 * @summary Reviews
 */
export const movieReviews = (
    movieId: number,
    params?: MovieReviewsParams,
 options?: SecondParameter<typeof tmdbClient<MovieReviews200>>,) => {
      return tmdbClient<MovieReviews200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/reviews`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the similar movies based on genres and keywords.
 * @summary Similar
 */
export const movieSimilar = (
    movieId: number,
    params?: MovieSimilarParams,
 options?: SecondParameter<typeof tmdbClient<MovieSimilar200>>,) => {
      return tmdbClient<MovieSimilar200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/similar`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the translations for a movie.
 * @summary Translations
 */
export const movieTranslations = (
    movieId: number,
 options?: SecondParameter<typeof tmdbClient<MovieTranslations200>>,) => {
      return tmdbClient<MovieTranslations200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/translations`, method: 'GET'
    },
      options);
    }

/**
 * @summary Videos
 */
export const movieVideos = (
    movieId: number,
    params?: MovieVideosParams,
 options?: SecondParameter<typeof tmdbClient<MovieVideos200>>,) => {
      return tmdbClient<MovieVideos200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/videos`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of streaming providers we have for a movie.
 * @summary Watch Providers
 */
export const movieWatchProviders = (
    movieId: number,
 options?: SecondParameter<typeof tmdbClient<MovieWatchProviders200>>,) => {
      return tmdbClient<MovieWatchProviders200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/watch/providers`, method: 'GET'
    },
      options);
    }

/**
 * Rate a movie and save it to your rated list.
 * @summary Add Rating
 */
export const movieAddRating = (
    movieId: number,
    movieAddRatingBody?: BodyType<MovieAddRatingBody>,
    params?: MovieAddRatingParams,
 options?: SecondParameter<typeof tmdbClient<MovieAddRating200>>,) => {
      return tmdbClient<MovieAddRating200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/rating`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: movieAddRatingBody,
        params
    },
      options);
    }

/**
 * Delete a user rating.
 * @summary Delete Rating
 */
export const movieDeleteRating = (
    movieId: number,
    params?: MovieDeleteRatingParams,
 options?: SecondParameter<typeof tmdbClient<MovieDeleteRating200>>,) => {
      return tmdbClient<MovieDeleteRating200>(
      {url: `https://api.themoviedb.org/3/movie/${movieId}/rating`, method: 'DELETE',
        params
    },
      options);
    }

/**
 * @summary Details
 */
export const networkDetails = (
    networkId: number,
 options?: SecondParameter<typeof tmdbClient<NetworkDetails200>>,) => {
      return tmdbClient<NetworkDetails200>(
      {url: `https://api.themoviedb.org/3/network/${networkId}`, method: 'GET'
    },
      options);
    }

/**
 * Get the alternative names of a network.
 * @summary Alternative Names
 */
export const detailsCopy = (
    networkId: number,
 options?: SecondParameter<typeof tmdbClient<DetailsCopy200>>,) => {
      return tmdbClient<DetailsCopy200>(
      {url: `https://api.themoviedb.org/3/network/${networkId}/alternative_names`, method: 'GET'
    },
      options);
    }

/**
 * Get the TV network logos by id.
 * @summary Images
 */
export const alternativeNamesCopy = (
    networkId: number,
 options?: SecondParameter<typeof tmdbClient<AlternativeNamesCopy200>>,) => {
      return tmdbClient<AlternativeNamesCopy200>(
      {url: `https://api.themoviedb.org/3/network/${networkId}/images`, method: 'GET'
    },
      options);
    }

/**
 * Get a list of people ordered by popularity.
 * @summary Popular
 */
export const personPopularList = (
    params?: PersonPopularListParams,
 options?: SecondParameter<typeof tmdbClient<PersonPopularList200>>,) => {
      return tmdbClient<PersonPopularList200>(
      {url: `https://api.themoviedb.org/3/person/popular`, method: 'GET',
        params
    },
      options);
    }

/**
 * Query the top level details of a person.
 * @summary Details
 */
export const personDetails = (
    personId: number,
    params?: PersonDetailsParams,
 options?: SecondParameter<typeof tmdbClient<PersonDetails200>>,) => {
      return tmdbClient<PersonDetails200>(
      {url: `https://api.themoviedb.org/3/person/${personId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the recent changes for a person.
 * @summary Changes
 */
export const personChanges = (
    personId: number,
    params?: PersonChangesParams,
 options?: SecondParameter<typeof tmdbClient<PersonChanges200>>,) => {
      return tmdbClient<PersonChanges200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the combined movie and TV credits that belong to a person.
 * @summary Combined Credits
 */
export const personCombinedCredits = (
    personId: string,
    params?: PersonCombinedCreditsParams,
 options?: SecondParameter<typeof tmdbClient<PersonCombinedCredits200>>,) => {
      return tmdbClient<PersonCombinedCredits200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/combined_credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the external ID's that belong to a person.
 * @summary External IDs
 */
export const personExternalIds = (
    personId: number,
 options?: SecondParameter<typeof tmdbClient<PersonExternalIds200>>,) => {
      return tmdbClient<PersonExternalIds200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/external_ids`, method: 'GET'
    },
      options);
    }

/**
 * Get the profile images that belong to a person.
 * @summary Images
 */
export const personImages = (
    personId: number,
 options?: SecondParameter<typeof tmdbClient<PersonImages200>>,) => {
      return tmdbClient<PersonImages200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/images`, method: 'GET'
    },
      options);
    }

/**
 * Get the newest created person. This is a live response and will continuously change.
 * @summary Latest
 */
export const personLatestId = (

 options?: SecondParameter<typeof tmdbClient<PersonLatestId200>>,) => {
      return tmdbClient<PersonLatestId200>(
      {url: `https://api.themoviedb.org/3/person/latest`, method: 'GET'
    },
      options);
    }

/**
 * Get the movie credits for a person.
 * @summary Movie Credits
 */
export const personMovieCredits = (
    personId: number,
    params?: PersonMovieCreditsParams,
 options?: SecondParameter<typeof tmdbClient<PersonMovieCredits200>>,) => {
      return tmdbClient<PersonMovieCredits200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/movie_credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the TV credits that belong to a person.
 * @summary TV Credits
 */
export const personTvCredits = (
    personId: number,
    params?: PersonTvCreditsParams,
 options?: SecondParameter<typeof tmdbClient<PersonTvCredits200>>,) => {
      return tmdbClient<PersonTvCredits200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/tv_credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the tagged images for a person.
 * @summary Tagged Images
 */
export const personTaggedImages = (
    personId: number,
    params?: PersonTaggedImagesParams,
 options?: SecondParameter<typeof tmdbClient<PersonTaggedImages200>>,) => {
      return tmdbClient<PersonTaggedImages200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/tagged_images`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the translations that belong to a person.
 * @summary Translations
 */
export const translations = (
    personId: number,
 options?: SecondParameter<typeof tmdbClient<Translations200>>,) => {
      return tmdbClient<Translations200>(
      {url: `https://api.themoviedb.org/3/person/${personId}/translations`, method: 'GET'
    },
      options);
    }

/**
 * Retrieve the details of a movie or TV show review.
 * @summary Details
 */
export const reviewDetails = (
    reviewId: string,
 options?: SecondParameter<typeof tmdbClient<ReviewDetails200>>,) => {
      return tmdbClient<ReviewDetails200>(
      {url: `https://api.themoviedb.org/3/review/${reviewId}`, method: 'GET'
    },
      options);
    }

/**
 * Search for collections by their original, translated and alternative names.
 * @summary Collection
 */
export const searchCollection = (
    params: SearchCollectionParams,
 options?: SecondParameter<typeof tmdbClient<SearchCollection200>>,) => {
      return tmdbClient<SearchCollection200>(
      {url: `https://api.themoviedb.org/3/search/collection`, method: 'GET',
        params
    },
      options);
    }

/**
 * Search for companies by their original and alternative names.
 * @summary Company
 */
export const searchCompany = (
    params: SearchCompanyParams,
 options?: SecondParameter<typeof tmdbClient<SearchCompany200>>,) => {
      return tmdbClient<SearchCompany200>(
      {url: `https://api.themoviedb.org/3/search/company`, method: 'GET',
        params
    },
      options);
    }

/**
 * Search for keywords by their name.
 * @summary Keyword
 */
export const searchKeyword = (
    params: SearchKeywordParams,
 options?: SecondParameter<typeof tmdbClient<SearchKeyword200>>,) => {
      return tmdbClient<SearchKeyword200>(
      {url: `https://api.themoviedb.org/3/search/keyword`, method: 'GET',
        params
    },
      options);
    }

/**
 * Search for movies by their original, translated and alternative titles.
 * @summary Movie
 */
export const searchMovie = (
    params: SearchMovieParams,
 options?: SecondParameter<typeof tmdbClient<SearchMovie200>>,) => {
      return tmdbClient<SearchMovie200>(
      {url: `https://api.themoviedb.org/3/search/movie`, method: 'GET',
        params
    },
      options);
    }

/**
 * Use multi search when you want to search for movies, TV shows and people in a single request.
 * @summary Multi
 */
export const searchMulti = (
    params: SearchMultiParams,
 options?: SecondParameter<typeof tmdbClient<SearchMulti200>>,) => {
      return tmdbClient<SearchMulti200>(
      {url: `https://api.themoviedb.org/3/search/multi`, method: 'GET',
        params
    },
      options);
    }

/**
 * Search for people by their name and also known as names.
 * @summary Person
 */
export const searchPerson = (
    params: SearchPersonParams,
 options?: SecondParameter<typeof tmdbClient<SearchPerson200>>,) => {
      return tmdbClient<SearchPerson200>(
      {url: `https://api.themoviedb.org/3/search/person`, method: 'GET',
        params
    },
      options);
    }

/**
 * Search for TV shows by their original, translated and also known as names.
 * @summary TV
 */
export const searchTv = (
    params: SearchTvParams,
 options?: SecondParameter<typeof tmdbClient<SearchTv200>>,) => {
      return tmdbClient<SearchTv200>(
      {url: `https://api.themoviedb.org/3/search/tv`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the trending movies, TV shows and people.
 * @summary All
 */
export const trendingAll = (
    params?: TrendingAllParams,
    timeWindow: 'day' | 'week' = 'day',
 options?: SecondParameter<typeof tmdbClient<TrendingAll200>>,) => {
      return tmdbClient<TrendingAll200>(
      {url: `https://api.themoviedb.org/3/trending/all/${timeWindow}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the trending movies on TMDB.
 * @summary Movies
 */
export const trendingMovies = (
    params?: TrendingMoviesParams,
    timeWindow: 'day' | 'week' = 'day',
 options?: SecondParameter<typeof tmdbClient<TrendingMovies200>>,) => {
      return tmdbClient<TrendingMovies200>(
      {url: `https://api.themoviedb.org/3/trending/movie/${timeWindow}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the trending people on TMDB.
 * @summary People
 */
export const trendingPeople = (
    params?: TrendingPeopleParams,
    timeWindow: 'day' | 'week' = 'day',
 options?: SecondParameter<typeof tmdbClient<TrendingPeople200>>,) => {
      return tmdbClient<TrendingPeople200>(
      {url: `https://api.themoviedb.org/3/trending/person/${timeWindow}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the trending TV shows on TMDB.
 * @summary TV
 */
export const trendingTv = (
    params?: TrendingTvParams,
    timeWindow: 'day' | 'week' = 'day',
 options?: SecondParameter<typeof tmdbClient<TrendingTv200>>,) => {
      return tmdbClient<TrendingTv200>(
      {url: `https://api.themoviedb.org/3/trending/tv/${timeWindow}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of TV shows airing today.
 * @summary Airing Today
 */
export const tvSeriesAiringTodayList = (
    params?: TvSeriesAiringTodayListParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesAiringTodayList200>>,) => {
      return tmdbClient<TvSeriesAiringTodayList200>(
      {url: `https://api.themoviedb.org/3/tv/airing_today`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of TV shows that air in the next 7 days.
 * @summary On The Air
 */
export const tvSeriesOnTheAirList = (
    params?: TvSeriesOnTheAirListParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesOnTheAirList200>>,) => {
      return tmdbClient<TvSeriesOnTheAirList200>(
      {url: `https://api.themoviedb.org/3/tv/on_the_air`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of TV shows ordered by popularity.
 * @summary Popular
 */
export const tvSeriesPopularList = (
    params?: TvSeriesPopularListParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesPopularList200>>,) => {
      return tmdbClient<TvSeriesPopularList200>(
      {url: `https://api.themoviedb.org/3/tv/popular`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of TV shows ordered by rating.
 * @summary Top Rated
 */
export const tvSeriesTopRatedList = (
    params?: TvSeriesTopRatedListParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesTopRatedList200>>,) => {
      return tmdbClient<TvSeriesTopRatedList200>(
      {url: `https://api.themoviedb.org/3/tv/top_rated`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the details of a TV show.
 * @summary Details
 */
export const tvSeriesDetails = (
    seriesId: number,
    params?: TvSeriesDetailsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesDetails200>>,) => {
      return tmdbClient<TvSeriesDetails200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rating, watchlist and favourite status.
 * @summary Account States
 */
export const tvSeriesAccountStates = (
    seriesId: number,
    params?: TvSeriesAccountStatesParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesAccountStates200>>,) => {
      return tmdbClient<TvSeriesAccountStates200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/account_states`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the aggregate credits (cast and crew) that have been added to a TV show.
 * @summary Aggregate Credits
 */
export const tvSeriesAggregateCredits = (
    seriesId: number,
    params?: TvSeriesAggregateCreditsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesAggregateCredits200>>,) => {
      return tmdbClient<TvSeriesAggregateCredits200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/aggregate_credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the alternative titles that have been added to a TV show.
 * @summary Alternative Titles
 */
export const tvSeriesAlternativeTitles = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesAlternativeTitles200>>,) => {
      return tmdbClient<TvSeriesAlternativeTitles200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/alternative_titles`, method: 'GET'
    },
      options);
    }

/**
 * Get the recent changes for a TV show.
 * @summary Changes
 */
export const tvSeriesChanges = (
    seriesId: number,
    params?: TvSeriesChangesParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesChanges200>>,) => {
      return tmdbClient<TvSeriesChanges200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the content ratings that have been added to a TV show.
 * @summary Content Ratings
 */
export const tvSeriesContentRatings = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesContentRatings200>>,) => {
      return tmdbClient<TvSeriesContentRatings200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/content_ratings`, method: 'GET'
    },
      options);
    }

/**
 * Get the latest season credits of a TV show.
 * @summary Credits
 */
export const tvSeriesCredits = (
    seriesId: number,
    params?: TvSeriesCreditsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesCredits200>>,) => {
      return tmdbClient<TvSeriesCredits200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the episode groups that have been added to a TV show.
 * @summary Episode Groups
 */
export const tvSeriesEpisodeGroups = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesEpisodeGroups200>>,) => {
      return tmdbClient<TvSeriesEpisodeGroups200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/episode_groups`, method: 'GET'
    },
      options);
    }

/**
 * Get a list of external IDs that have been added to a TV show.
 * @summary External IDs
 */
export const tvSeriesExternalIds = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesExternalIds200>>,) => {
      return tmdbClient<TvSeriesExternalIds200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/external_ids`, method: 'GET'
    },
      options);
    }

/**
 * Get the images that belong to a TV series.
 * @summary Images
 */
export const tvSeriesImages = (
    seriesId: number,
    params?: TvSeriesImagesParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesImages200>>,) => {
      return tmdbClient<TvSeriesImages200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/images`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of keywords that have been added to a TV show.
 * @summary Keywords
 */
export const tvSeriesKeywords = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesKeywords200>>,) => {
      return tmdbClient<TvSeriesKeywords200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/keywords`, method: 'GET'
    },
      options);
    }

/**
 * Get the newest TV show ID.
 * @summary Latest
 */
export const tvSeriesLatestId = (

 options?: SecondParameter<typeof tmdbClient<TvSeriesLatestId200>>,) => {
      return tmdbClient<TvSeriesLatestId200>(
      {url: `https://api.themoviedb.org/3/tv/latest`, method: 'GET'
    },
      options);
    }

/**
 * Get the lists that a TV series has been added to.
 * @summary Lists
 */
export const listsCopy = (
    seriesId: number,
    params?: ListsCopyParams,
 options?: SecondParameter<typeof tmdbClient<ListsCopy200>>,) => {
      return tmdbClient<ListsCopy200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/lists`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Recommendations
 */
export const tvSeriesRecommendations = (
    seriesId: number,
    params?: TvSeriesRecommendationsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesRecommendations200>>,) => {
      return tmdbClient<TvSeriesRecommendations200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/recommendations`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the reviews that have been added to a TV show.
 * @summary Reviews
 */
export const tvSeriesReviews = (
    seriesId: number,
    params?: TvSeriesReviewsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesReviews200>>,) => {
      return tmdbClient<TvSeriesReviews200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/reviews`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the seasons and episodes that have screened theatrically.
 * @summary Screened Theatrically
 */
export const tvSeriesScreenedTheatrically = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesScreenedTheatrically200>>,) => {
      return tmdbClient<TvSeriesScreenedTheatrically200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/screened_theatrically`, method: 'GET'
    },
      options);
    }

/**
 * Get the similar TV shows.
 * @summary Similar
 */
export const tvSeriesSimilar = (
    seriesId: string,
    params?: TvSeriesSimilarParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesSimilar200>>,) => {
      return tmdbClient<TvSeriesSimilar200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/similar`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the translations that have been added to a TV show.
 * @summary Translations
 */
export const tvSeriesTranslations = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesTranslations200>>,) => {
      return tmdbClient<TvSeriesTranslations200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/translations`, method: 'GET'
    },
      options);
    }

/**
 * Get the videos that belong to a TV show.
 * @summary Videos
 */
export const tvSeriesVideos = (
    seriesId: number,
    params?: TvSeriesVideosParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesVideos200>>,) => {
      return tmdbClient<TvSeriesVideos200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/videos`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of streaming providers we have for a TV show.
 * @summary Watch Providers
 */
export const tvSeriesWatchProviders = (
    seriesId: number,
 options?: SecondParameter<typeof tmdbClient<TvSeriesWatchProviders200>>,) => {
      return tmdbClient<TvSeriesWatchProviders200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/watch/providers`, method: 'GET'
    },
      options);
    }

/**
 * Rate a TV show and save it to your rated list.
 * @summary Add Rating
 */
export const tvSeriesAddRating = (
    seriesId: number,
    tvSeriesAddRatingBody?: BodyType<TvSeriesAddRatingBody>,
    params?: TvSeriesAddRatingParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesAddRating200>>,) => {
      return tmdbClient<TvSeriesAddRating200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/rating`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tvSeriesAddRatingBody,
        params
    },
      options);
    }

/**
 * @summary Delete Rating
 */
export const tvSeriesDeleteRating = (
    seriesId: number,
    params?: TvSeriesDeleteRatingParams,
 options?: SecondParameter<typeof tmdbClient<TvSeriesDeleteRating200>>,) => {
      return tmdbClient<TvSeriesDeleteRating200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/rating`, method: 'DELETE',
        params
    },
      options);
    }

/**
 * Query the details of a TV season.
 * @summary Details
 */
export const tvSeasonDetails = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonDetailsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonDetails200>>,) => {
      return tmdbClient<TvSeasonDetails200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rating, watchlist and favourite status.
 * @summary Account States
 */
export const tvSeasonAccountStates = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonAccountStatesParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonAccountStates200>>,) => {
      return tmdbClient<TvSeasonAccountStates200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/account_states`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the aggregate credits (cast and crew) that have been added to a TV season.
 * @summary Aggregate Credits
 */
export const tvSeasonAggregateCredits = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonAggregateCreditsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonAggregateCredits200>>,) => {
      return tmdbClient<TvSeasonAggregateCredits200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/aggregate_credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the recent changes for a TV season.
 * @summary Changes
 */
export const tvSeasonChangesById = (
    seasonId: number,
    params?: TvSeasonChangesByIdParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonChangesById200>>,) => {
      return tmdbClient<TvSeasonChangesById200>(
      {url: `https://api.themoviedb.org/3/tv/season/${seasonId}/changes`, method: 'GET',
        params
    },
      options);
    }

/**
 * @summary Credits
 */
export const tvSeasonCredits = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonCreditsParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonCredits200>>,) => {
      return tmdbClient<TvSeasonCredits200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of external IDs that have been added to a TV season.
 * @summary External IDs
 */
export const tvSeasonExternalIds = (
    seriesId: number,
    seasonNumber: number,
 options?: SecondParameter<typeof tmdbClient<TvSeasonExternalIds200>>,) => {
      return tmdbClient<TvSeasonExternalIds200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/external_ids`, method: 'GET'
    },
      options);
    }

/**
 * Get the images that belong to a TV season.
 * @summary Images
 */
export const tvSeasonImages = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonImagesParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonImages200>>,) => {
      return tmdbClient<TvSeasonImages200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/images`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the translations for a TV season.
 * @summary Translations
 */
export const tvSeasonTranslations = (
    seriesId: number,
    seasonNumber: number,
 options?: SecondParameter<typeof tmdbClient<TvSeasonTranslations200>>,) => {
      return tmdbClient<TvSeasonTranslations200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/translations`, method: 'GET'
    },
      options);
    }

/**
 * Get the videos that belong to a TV season.
 * @summary Videos
 */
export const tvSeasonVideos = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonVideosParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonVideos200>>,) => {
      return tmdbClient<TvSeasonVideos200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/videos`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of streaming providers we have for a TV season.
 * @summary Watch Providers
 */
export const tvSeasonWatchProviders = (
    seriesId: number,
    seasonNumber: number,
    params?: TvSeasonWatchProvidersParams,
 options?: SecondParameter<typeof tmdbClient<TvSeasonWatchProviders200>>,) => {
      return tmdbClient<TvSeasonWatchProviders200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/watch/providers`, method: 'GET',
        params
    },
      options);
    }

/**
 * Query the details of a TV episode.
 * @summary Details
 */
export const tvEpisodeDetails = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeDetailsParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeDetails200>>,) => {
      return tmdbClient<TvEpisodeDetails200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the rating, watchlist and favourite status.
 * @summary Account States
 */
export const tvEpisodeAccountStates = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeAccountStatesParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeAccountStates200>>,) => {
      return tmdbClient<TvEpisodeAccountStates200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/account_states`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the recent changes for a TV episode.
 * @summary Changes
 */
export const tvEpisodeChangesById = (
    episodeId: number,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeChangesById200>>,) => {
      return tmdbClient<TvEpisodeChangesById200>(
      {url: `https://api.themoviedb.org/3/tv/episode/${episodeId}/changes`, method: 'GET'
    },
      options);
    }

/**
 * @summary Credits
 */
export const tvEpisodeCredits = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeCreditsParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeCredits200>>,) => {
      return tmdbClient<TvEpisodeCredits200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/credits`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get a list of external IDs that have been added to a TV episode.
 * @summary External IDs
 */
export const tvEpisodeExternalIds = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: string,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeExternalIds200>>,) => {
      return tmdbClient<TvEpisodeExternalIds200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/external_ids`, method: 'GET'
    },
      options);
    }

/**
 * Get the images that belong to a TV episode.
 * @summary Images
 */
export const tvEpisodeImages = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeImagesParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeImages200>>,) => {
      return tmdbClient<TvEpisodeImages200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/images`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the translations that have been added to a TV episode.
 * @summary Translations
 */
export const tvEpisodeTranslations = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeTranslations200>>,) => {
      return tmdbClient<TvEpisodeTranslations200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/translations`, method: 'GET'
    },
      options);
    }

/**
 * Get the videos that belong to a TV episode.
 * @summary Videos
 */
export const tvEpisodeVideos = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeVideosParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeVideos200>>,) => {
      return tmdbClient<TvEpisodeVideos200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/videos`, method: 'GET',
        params
    },
      options);
    }

/**
 * Rate a TV episode and save it to your rated list.
 * @summary Add Rating
 */
export const tvEpisodeAddRating = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    tvEpisodeAddRatingBody?: BodyType<TvEpisodeAddRatingBody>,
    params?: TvEpisodeAddRatingParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeAddRating200>>,) => {
      return tmdbClient<TvEpisodeAddRating200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/rating`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tvEpisodeAddRatingBody,
        params
    },
      options);
    }

/**
 * Delete your rating on a TV episode.
 * @summary Delete Rating
 */
export const tvEpisodeDeleteRating = (
    seriesId: number,
    seasonNumber: number,
    episodeNumber: number,
    params?: TvEpisodeDeleteRatingParams,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeDeleteRating200>>,) => {
      return tmdbClient<TvEpisodeDeleteRating200>(
      {url: `https://api.themoviedb.org/3/tv/${seriesId}/season/${seasonNumber}/episode/${episodeNumber}/rating`, method: 'DELETE',
        params
    },
      options);
    }

/**
 * Get the details of a TV episode group.
 * @summary Details
 */
export const tvEpisodeGroupDetails = (
    tvEpisodeGroupId: string,
 options?: SecondParameter<typeof tmdbClient<TvEpisodeGroupDetails200>>,) => {
      return tmdbClient<TvEpisodeGroupDetails200>(
      {url: `https://api.themoviedb.org/3/tv/episode_group/${tvEpisodeGroupId}`, method: 'GET'
    },
      options);
    }

/**
 * Get the list of the countries we have watch provider (OTT/streaming) data for.
 * @summary Available Regions
 */
export const watchProvidersAvailableRegions = (
    params?: WatchProvidersAvailableRegionsParams,
 options?: SecondParameter<typeof tmdbClient<WatchProvidersAvailableRegions200>>,) => {
      return tmdbClient<WatchProvidersAvailableRegions200>(
      {url: `https://api.themoviedb.org/3/watch/providers/regions`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of streaming providers we have for movies.
 * @summary Movie Providers
 */
export const watchProvidersMovieList = (
    params?: WatchProvidersMovieListParams,
 options?: SecondParameter<typeof tmdbClient<WatchProvidersMovieList200>>,) => {
      return tmdbClient<WatchProvidersMovieList200>(
      {url: `https://api.themoviedb.org/3/watch/providers/movie`, method: 'GET',
        params
    },
      options);
    }

/**
 * Get the list of streaming providers we have for TV shows.
 * @summary TV Providers
 */
export const watchProviderTvList = (
    params?: WatchProviderTvListParams,
 options?: SecondParameter<typeof tmdbClient<WatchProviderTvList200>>,) => {
      return tmdbClient<WatchProviderTvList200>(
      {url: `https://api.themoviedb.org/3/watch/providers/tv`, method: 'GET',
        params
    },
      options);
    }

export type AuthenticationValidateKeyResult = NonNullable<Awaited<ReturnType<typeof authenticationValidateKey>>>
export type AccountDetailsResult = NonNullable<Awaited<ReturnType<typeof accountDetails>>>
export type AccountAddFavoriteResult = NonNullable<Awaited<ReturnType<typeof accountAddFavorite>>>
export type AccountAddToWatchlistResult = NonNullable<Awaited<ReturnType<typeof accountAddToWatchlist>>>
export type AccountGetFavoritesResult = NonNullable<Awaited<ReturnType<typeof accountGetFavorites>>>
export type AccountFavoriteTvResult = NonNullable<Awaited<ReturnType<typeof accountFavoriteTv>>>
export type AccountListsResult = NonNullable<Awaited<ReturnType<typeof accountLists>>>
export type AccountRatedMoviesResult = NonNullable<Awaited<ReturnType<typeof accountRatedMovies>>>
export type AccountRatedTvResult = NonNullable<Awaited<ReturnType<typeof accountRatedTv>>>
export type AccountRatedTvEpisodesResult = NonNullable<Awaited<ReturnType<typeof accountRatedTvEpisodes>>>
export type AccountWatchlistMoviesResult = NonNullable<Awaited<ReturnType<typeof accountWatchlistMovies>>>
export type AccountWatchlistTvResult = NonNullable<Awaited<ReturnType<typeof accountWatchlistTv>>>
export type AuthenticationCreateGuestSessionResult = NonNullable<Awaited<ReturnType<typeof authenticationCreateGuestSession>>>
export type AuthenticationCreateRequestTokenResult = NonNullable<Awaited<ReturnType<typeof authenticationCreateRequestToken>>>
export type AuthenticationCreateSessionResult = NonNullable<Awaited<ReturnType<typeof authenticationCreateSession>>>
export type AuthenticationCreateSessionFromV4TokenResult = NonNullable<Awaited<ReturnType<typeof authenticationCreateSessionFromV4Token>>>
export type AuthenticationCreateSessionFromLoginResult = NonNullable<Awaited<ReturnType<typeof authenticationCreateSessionFromLogin>>>
export type AuthenticationDeleteSessionResult = NonNullable<Awaited<ReturnType<typeof authenticationDeleteSession>>>
export type CertificationMovieListResult = NonNullable<Awaited<ReturnType<typeof certificationMovieList>>>
export type CertificationsTvListResult = NonNullable<Awaited<ReturnType<typeof certificationsTvList>>>
export type ChangesMovieListResult = NonNullable<Awaited<ReturnType<typeof changesMovieList>>>
export type ChangesPeopleListResult = NonNullable<Awaited<ReturnType<typeof changesPeopleList>>>
export type ChangesTvListResult = NonNullable<Awaited<ReturnType<typeof changesTvList>>>
export type CollectionDetailsResult = NonNullable<Awaited<ReturnType<typeof collectionDetails>>>
export type CollectionImagesResult = NonNullable<Awaited<ReturnType<typeof collectionImages>>>
export type CollectionTranslationsResult = NonNullable<Awaited<ReturnType<typeof collectionTranslations>>>
export type CompanyDetailsResult = NonNullable<Awaited<ReturnType<typeof companyDetails>>>
export type CompanyAlternativeNamesResult = NonNullable<Awaited<ReturnType<typeof companyAlternativeNames>>>
export type CompanyImagesResult = NonNullable<Awaited<ReturnType<typeof companyImages>>>
export type ConfigurationDetailsResult = NonNullable<Awaited<ReturnType<typeof configurationDetails>>>
export type ConfigurationCountriesResult = NonNullable<Awaited<ReturnType<typeof configurationCountries>>>
export type ConfigurationJobsResult = NonNullable<Awaited<ReturnType<typeof configurationJobs>>>
export type ConfigurationLanguagesResult = NonNullable<Awaited<ReturnType<typeof configurationLanguages>>>
export type ConfigurationPrimaryTranslationsResult = NonNullable<Awaited<ReturnType<typeof configurationPrimaryTranslations>>>
export type ConfigurationTimezonesResult = NonNullable<Awaited<ReturnType<typeof configurationTimezones>>>
export type CreditDetailsResult = NonNullable<Awaited<ReturnType<typeof creditDetails>>>
export type DiscoverMovieResult = NonNullable<Awaited<ReturnType<typeof discoverMovie>>>
export type DiscoverTvResult = NonNullable<Awaited<ReturnType<typeof discoverTv>>>
export type FindByIdResult = NonNullable<Awaited<ReturnType<typeof findById>>>
export type GenreMovieListResult = NonNullable<Awaited<ReturnType<typeof genreMovieList>>>
export type GenreTvListResult = NonNullable<Awaited<ReturnType<typeof genreTvList>>>
export type GuestSessionRatedMoviesResult = NonNullable<Awaited<ReturnType<typeof guestSessionRatedMovies>>>
export type GuestSessionRatedTvResult = NonNullable<Awaited<ReturnType<typeof guestSessionRatedTv>>>
export type GuestSessionRatedTvEpisodesResult = NonNullable<Awaited<ReturnType<typeof guestSessionRatedTvEpisodes>>>
export type KeywordDetailsResult = NonNullable<Awaited<ReturnType<typeof keywordDetails>>>
export type KeywordMoviesResult = NonNullable<Awaited<ReturnType<typeof keywordMovies>>>
export type ListAddMovieResult = NonNullable<Awaited<ReturnType<typeof listAddMovie>>>
export type ListCheckItemStatusResult = NonNullable<Awaited<ReturnType<typeof listCheckItemStatus>>>
export type ListClearResult = NonNullable<Awaited<ReturnType<typeof listClear>>>
export type ListCreateResult = NonNullable<Awaited<ReturnType<typeof listCreate>>>
export type ListDeleteResult = NonNullable<Awaited<ReturnType<typeof listDelete>>>
export type ListDetailsResult = NonNullable<Awaited<ReturnType<typeof listDetails>>>
export type ListRemoveMovieResult = NonNullable<Awaited<ReturnType<typeof listRemoveMovie>>>
export type MovieNowPlayingListResult = NonNullable<Awaited<ReturnType<typeof movieNowPlayingList>>>
export type MoviePopularListResult = NonNullable<Awaited<ReturnType<typeof moviePopularList>>>
export type MovieTopRatedListResult = NonNullable<Awaited<ReturnType<typeof movieTopRatedList>>>
export type MovieUpcomingListResult = NonNullable<Awaited<ReturnType<typeof movieUpcomingList>>>
export type MovieDetailsResult = NonNullable<Awaited<ReturnType<typeof movieDetails>>>
export type MovieAccountStatesResult = NonNullable<Awaited<ReturnType<typeof movieAccountStates>>>
export type MovieAlternativeTitlesResult = NonNullable<Awaited<ReturnType<typeof movieAlternativeTitles>>>
export type MovieChangesResult = NonNullable<Awaited<ReturnType<typeof movieChanges>>>
export type MovieCreditsResult = NonNullable<Awaited<ReturnType<typeof movieCredits>>>
export type MovieExternalIdsResult = NonNullable<Awaited<ReturnType<typeof movieExternalIds>>>
export type MovieImagesResult = NonNullable<Awaited<ReturnType<typeof movieImages>>>
export type MovieKeywordsResult = NonNullable<Awaited<ReturnType<typeof movieKeywords>>>
export type MovieLatestIdResult = NonNullable<Awaited<ReturnType<typeof movieLatestId>>>
export type MovieListsResult = NonNullable<Awaited<ReturnType<typeof movieLists>>>
export type MovieRecommendationsResult = NonNullable<Awaited<ReturnType<typeof movieRecommendations>>>
export type MovieReleaseDatesResult = NonNullable<Awaited<ReturnType<typeof movieReleaseDates>>>
export type MovieReviewsResult = NonNullable<Awaited<ReturnType<typeof movieReviews>>>
export type MovieSimilarResult = NonNullable<Awaited<ReturnType<typeof movieSimilar>>>
export type MovieTranslationsResult = NonNullable<Awaited<ReturnType<typeof movieTranslations>>>
export type MovieVideosResult = NonNullable<Awaited<ReturnType<typeof movieVideos>>>
export type MovieWatchProvidersResult = NonNullable<Awaited<ReturnType<typeof movieWatchProviders>>>
export type MovieAddRatingResult = NonNullable<Awaited<ReturnType<typeof movieAddRating>>>
export type MovieDeleteRatingResult = NonNullable<Awaited<ReturnType<typeof movieDeleteRating>>>
export type NetworkDetailsResult = NonNullable<Awaited<ReturnType<typeof networkDetails>>>
export type DetailsCopyResult = NonNullable<Awaited<ReturnType<typeof detailsCopy>>>
export type AlternativeNamesCopyResult = NonNullable<Awaited<ReturnType<typeof alternativeNamesCopy>>>
export type PersonPopularListResult = NonNullable<Awaited<ReturnType<typeof personPopularList>>>
export type PersonDetailsResult = NonNullable<Awaited<ReturnType<typeof personDetails>>>
export type PersonChangesResult = NonNullable<Awaited<ReturnType<typeof personChanges>>>
export type PersonCombinedCreditsResult = NonNullable<Awaited<ReturnType<typeof personCombinedCredits>>>
export type PersonExternalIdsResult = NonNullable<Awaited<ReturnType<typeof personExternalIds>>>
export type PersonImagesResult = NonNullable<Awaited<ReturnType<typeof personImages>>>
export type PersonLatestIdResult = NonNullable<Awaited<ReturnType<typeof personLatestId>>>
export type PersonMovieCreditsResult = NonNullable<Awaited<ReturnType<typeof personMovieCredits>>>
export type PersonTvCreditsResult = NonNullable<Awaited<ReturnType<typeof personTvCredits>>>
export type PersonTaggedImagesResult = NonNullable<Awaited<ReturnType<typeof personTaggedImages>>>
export type TranslationsResult = NonNullable<Awaited<ReturnType<typeof translations>>>
export type ReviewDetailsResult = NonNullable<Awaited<ReturnType<typeof reviewDetails>>>
export type SearchCollectionResult = NonNullable<Awaited<ReturnType<typeof searchCollection>>>
export type SearchCompanyResult = NonNullable<Awaited<ReturnType<typeof searchCompany>>>
export type SearchKeywordResult = NonNullable<Awaited<ReturnType<typeof searchKeyword>>>
export type SearchMovieResult = NonNullable<Awaited<ReturnType<typeof searchMovie>>>
export type SearchMultiResult = NonNullable<Awaited<ReturnType<typeof searchMulti>>>
export type SearchPersonResult = NonNullable<Awaited<ReturnType<typeof searchPerson>>>
export type SearchTvResult = NonNullable<Awaited<ReturnType<typeof searchTv>>>
export type TrendingAllResult = NonNullable<Awaited<ReturnType<typeof trendingAll>>>
export type TrendingMoviesResult = NonNullable<Awaited<ReturnType<typeof trendingMovies>>>
export type TrendingPeopleResult = NonNullable<Awaited<ReturnType<typeof trendingPeople>>>
export type TrendingTvResult = NonNullable<Awaited<ReturnType<typeof trendingTv>>>
export type TvSeriesAiringTodayListResult = NonNullable<Awaited<ReturnType<typeof tvSeriesAiringTodayList>>>
export type TvSeriesOnTheAirListResult = NonNullable<Awaited<ReturnType<typeof tvSeriesOnTheAirList>>>
export type TvSeriesPopularListResult = NonNullable<Awaited<ReturnType<typeof tvSeriesPopularList>>>
export type TvSeriesTopRatedListResult = NonNullable<Awaited<ReturnType<typeof tvSeriesTopRatedList>>>
export type TvSeriesDetailsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesDetails>>>
export type TvSeriesAccountStatesResult = NonNullable<Awaited<ReturnType<typeof tvSeriesAccountStates>>>
export type TvSeriesAggregateCreditsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesAggregateCredits>>>
export type TvSeriesAlternativeTitlesResult = NonNullable<Awaited<ReturnType<typeof tvSeriesAlternativeTitles>>>
export type TvSeriesChangesResult = NonNullable<Awaited<ReturnType<typeof tvSeriesChanges>>>
export type TvSeriesContentRatingsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesContentRatings>>>
export type TvSeriesCreditsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesCredits>>>
export type TvSeriesEpisodeGroupsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesEpisodeGroups>>>
export type TvSeriesExternalIdsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesExternalIds>>>
export type TvSeriesImagesResult = NonNullable<Awaited<ReturnType<typeof tvSeriesImages>>>
export type TvSeriesKeywordsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesKeywords>>>
export type TvSeriesLatestIdResult = NonNullable<Awaited<ReturnType<typeof tvSeriesLatestId>>>
export type ListsCopyResult = NonNullable<Awaited<ReturnType<typeof listsCopy>>>
export type TvSeriesRecommendationsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesRecommendations>>>
export type TvSeriesReviewsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesReviews>>>
export type TvSeriesScreenedTheatricallyResult = NonNullable<Awaited<ReturnType<typeof tvSeriesScreenedTheatrically>>>
export type TvSeriesSimilarResult = NonNullable<Awaited<ReturnType<typeof tvSeriesSimilar>>>
export type TvSeriesTranslationsResult = NonNullable<Awaited<ReturnType<typeof tvSeriesTranslations>>>
export type TvSeriesVideosResult = NonNullable<Awaited<ReturnType<typeof tvSeriesVideos>>>
export type TvSeriesWatchProvidersResult = NonNullable<Awaited<ReturnType<typeof tvSeriesWatchProviders>>>
export type TvSeriesAddRatingResult = NonNullable<Awaited<ReturnType<typeof tvSeriesAddRating>>>
export type TvSeriesDeleteRatingResult = NonNullable<Awaited<ReturnType<typeof tvSeriesDeleteRating>>>
export type TvSeasonDetailsResult = NonNullable<Awaited<ReturnType<typeof tvSeasonDetails>>>
export type TvSeasonAccountStatesResult = NonNullable<Awaited<ReturnType<typeof tvSeasonAccountStates>>>
export type TvSeasonAggregateCreditsResult = NonNullable<Awaited<ReturnType<typeof tvSeasonAggregateCredits>>>
export type TvSeasonChangesByIdResult = NonNullable<Awaited<ReturnType<typeof tvSeasonChangesById>>>
export type TvSeasonCreditsResult = NonNullable<Awaited<ReturnType<typeof tvSeasonCredits>>>
export type TvSeasonExternalIdsResult = NonNullable<Awaited<ReturnType<typeof tvSeasonExternalIds>>>
export type TvSeasonImagesResult = NonNullable<Awaited<ReturnType<typeof tvSeasonImages>>>
export type TvSeasonTranslationsResult = NonNullable<Awaited<ReturnType<typeof tvSeasonTranslations>>>
export type TvSeasonVideosResult = NonNullable<Awaited<ReturnType<typeof tvSeasonVideos>>>
export type TvSeasonWatchProvidersResult = NonNullable<Awaited<ReturnType<typeof tvSeasonWatchProviders>>>
export type TvEpisodeDetailsResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeDetails>>>
export type TvEpisodeAccountStatesResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeAccountStates>>>
export type TvEpisodeChangesByIdResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeChangesById>>>
export type TvEpisodeCreditsResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeCredits>>>
export type TvEpisodeExternalIdsResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeExternalIds>>>
export type TvEpisodeImagesResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeImages>>>
export type TvEpisodeTranslationsResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeTranslations>>>
export type TvEpisodeVideosResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeVideos>>>
export type TvEpisodeAddRatingResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeAddRating>>>
export type TvEpisodeDeleteRatingResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeDeleteRating>>>
export type TvEpisodeGroupDetailsResult = NonNullable<Awaited<ReturnType<typeof tvEpisodeGroupDetails>>>
export type WatchProvidersAvailableRegionsResult = NonNullable<Awaited<ReturnType<typeof watchProvidersAvailableRegions>>>
export type WatchProvidersMovieListResult = NonNullable<Awaited<ReturnType<typeof watchProvidersMovieList>>>
export type WatchProviderTvListResult = NonNullable<Awaited<ReturnType<typeof watchProviderTvList>>>
